name: Build, Test, and Lint

on:
  push:
    branches:
      - main
      - feat/further-gpu-acceleration
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**/*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint and Format Check
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy (macOS)
        run: cargo clippy --all-targets -- -D warnings
      - name: Run Clippy (iOS)
        run: cargo clippy --all-targets --features "h2c ios-bindings" --no-default-features -- -D warnings

  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: rustup target add aarch64-apple-ios
      - name: Run Main Tests (Halo2Curves Backend)
        env:
          RUST_LOG: debug
        run: cargo test --release --features "ark h2c ark macos" --no-default-features
      - name: Run Ignored Tests (Ark Backend)
        env:
          RUST_LOG: debug
        run: cargo test --release --features "ark macos" --no-default-features -- --ignored --test-threads=1

  build:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: rustup target add aarch64-apple-ios
      - name: Build for iOS
        run: cargo run --release --bin gen_ios_bindings --features "h2c ios-bindings" --no-default-features